name: xRepeller
version: 2.3
description: The ultimate Civilization Forum Plugin - New Version

author: xasz
website: https://github.com/xasz/xRepeller
main: me.xasz.xRepeller.xRepeller
permissions:
  xRepeller.create:
    description: Allows you to create
    default: true
  xRepeller.destroy:
    description: Allows you to destroy
    default: true
  xRepeller.check:
    description: Allows you to check a repeller
    default: true